name: Go

on: push

jobs:

  Tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: hello-world
      run: |
        cd hello-world
        go test -v
    
    - name: integers
      run: |
        cd integers
        go test -v
        go test -cover
    
    - name: iteration
      run: |
        cd iteration
        go test -v
        go test -cover
    
    - name: arrays-and-slices
      run: |
        cd arrays-and-slices
        go test -v
        go test -cover
